services:
  - type: web
    name: lalitha-pharmacy-api
    runtime: node
    plan: free
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        fromDatabase:
          name: lalitha-pharmacy-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://lalitha-pharmacy-1.onrender.com,https://lalitha-pharmacy.onrender.com
      - key: SESSION_SECRET
        generateValue: true

  - type: web
    name: lalitha-pharmacy-frontend
    runtime: node
    plan: free
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm run preview"
    envVars:
      - key: VITE_API_URL
        value: https://lalitha-pharmacy.onrender.com/api

databases:
  - name: lalitha-pharmacy-db
    plan: free
